### ISSUE TITLE
chrome version error 

### ISSUE THREAD

**Issue by cjrayance** [TAJLNsScripts/iq.com-downloader#2]
```C:\Users\Administrator\Downloads\iq.com-downloader-main>python iq.py
Initializing selenium
could not detect version_main.therefore, we are assuming it is chrome 108 or higher
Message: unknown error: cannot connect to chrome at 127.0.0.1:6081
from session not created: This version of ChromeDriver only supports Chrome version 111
Current browser version is 115.0.5790.170
Stacktrace:
Backtrace:
        (No symbol) [0x00B1DCE3]
        (No symbol) [0x00AB39D1]
        (No symbol) [0x009C4DA8]
        (No symbol) [0x009E4F6C]
        (No symbol) [0x009DEE51]
        (No symbol) [0x009DEC31]
        (No symbol) [0x00A115AE]
        (No symbol) [0x00A1129C]
        (No symbol) [0x00A0ACC6]
        (No symbol) [0x009E6F68]
        (No symbol) [0x009E80CD]
        GetHandleVerifier [0x00D93832+2506274]
        GetHandleVerifier [0x00DC9794+2727300]
        GetHandleVerifier [0x00DCE36C+2746716]
        GetHandleVerifier [0x00BC6690+617600]
        (No symbol) [0x00ABC712]
        (No symbol) [0x00AC1FF8]
        (No symbol) [0x00AC20DB]
        (No symbol) [0x00ACC63B]
        BaseThreadInitThunk [0x75DE6359+25]
        RtlGetAppContainerNamedObjectPath [0x77AB87A4+228]
        RtlGetAppContainerNamedObjectPath [0x77AB8774+180]


Bye :)
Error in sys.excepthook:
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\iq.com-downloader-main\iq.py", line 24, in myexcepthook
    s_exit()
  File "C:\Users\Administrator\Downloads\iq.com-downloader-main\iq.py", line 36, in s_exit
    driver.quit()
NameError: name 'driver' is not defined

Original exception was:
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\iq.com-downloader-main\iq.py", line 285, in <module>
    driver = selenium_init()
  File "C:\Users\Administrator\Downloads\iq.com-downloader-main\iq.py", line 64, in selenium_init
    driver = uc.Chrome(options=options)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\seleniumwire\undetected_chromedriver\webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\undetected_chromedriver\__init__.py", line 443, in __init__
    super(Chrome, self).__init__(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 49, in __init__
    super().__init__(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 54, in __init__
    super().__init__(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\undetected_chromedriver\__init__.py", line 674, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 291, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:6081
from session not created: This version of ChromeDriver only supports Chrome version 111
Current browser version is 115.0.5790.170
Stacktrace:
Backtrace:
        (No symbol) [0x00B1DCE3]
        (No symbol) [0x00AB39D1]
        (No symbol) [0x009C4DA8]
        (No symbol) [0x009E4F6C]
        (No symbol) [0x009DEE51]
        (No symbol) [0x009DEC31]
        (No symbol) [0x00A115AE]
        (No symbol) [0x00A1129C]
        (No symbol) [0x00A0ACC6]
        (No symbol) [0x009E6F68]
        (No symbol) [0x009E80CD]
        GetHandleVerifier [0x00D93832+2506274]
        GetHandleVerifier [0x00DC9794+2727300]
        GetHandleVerifier [0x00DCE36C+2746716]
        GetHandleVerifier [0x00BC6690+617600]
        (No symbol) [0x00ABC712]
        (No symbol) [0x00AC1FF8]
        (No symbol) [0x00AC20DB]
        (No symbol) [0x00ACC63B]
        BaseThreadInitThunk [0x75DE6359+25]
        RtlGetAppContainerNamedObjectPath [0x77AB87A4+228]
        RtlGetAppContainerNamedObjectPath [0x77AB8774+180]```

**Comment by cjrayance** [comment]
I fixed it by downloading chromedriver.exe to match the version of GoogleChrome and pasting it to C:\Users\admin\AppData\Roaming\undetected_chromedriver error is missing, but a new problem is unable to login.

**Comment by TAJLNsScripts** [comment]
I can't reproduce your issue, if you have trouble logging in, you can login normally in your google chrome and then copy User Data from your chrome to UserData folder next to your iq.py script

**Comment by cjrayance** [comment]
Now I have reinstalled windows and it works fine. 

copy User Data from google chrome PATH is also a method that works.

Now the problem I encounter is when wanting to download a title that has more than 50 EPs or more or has many pages as shown in Figure 1, for example 
![Screenshot 2023-09-13 133148](https://github.com/TAJLNsScripts/iq.com-downloader/assets/122617363/787b5fee-4191-48ec-8ebb-9aaf0b01d2ba)

[https://www.iq.com/album/boruto-naruto-next-generations-2021-2eogugt8pj5?lang=en_us](url) 

It downloads only 50Episode even though there are only 150 EPs in total. Can you please check and fix it? Thank you very much.
